### ISSUE TITLE
Allow kicking a user

### ISSUE THREAD

**Issue by meghanmae** [Keboo/PointerStar#281]
Use case: Kevin leaves for another meeting and skews all the remaining votes. :)

**Comment by Keboo** [comment]
This is not actually possible since the client will just automatically reconnect (assuming they leave their browser open). Because there is not auth the only way we identify users is via their SignalR connection. However, anyone with the Facilitator role can demote people out of the Team Members list as into an observer role with this button:
![image](https://github.com/Keboo/PointerStar/assets/952248/9637961b-5860-4a66-99b5-64857efc5371)
